Feat/create user
Move-HandsOn/move-backend pull request #4
Opened 2024-09-26 20:02 UTC by nanerseasac

2024-09-26 20:45 UTC, jauregao requested changes

2024-09-26 20:45 UTC, jauregao commented on .env.example
Edite o database url no seu arquivo .env local, o .env.example existe para servir de exemplo somente.

2024-09-26 20:45 UTC, jauregao commented on src/users/users.controller.ts
> +    const hashedPassword = await bcrypt.hash(createUserDto.password, 10);
Não faça regra de negócio no controlador.
Crie um método no service que irá criptografar a senha antes de cadastrar no banco de dados.

2024-09-26 20:45 UTC, jauregao commented on src/users/users.controller.ts
>    @Get(':id')
É necessário entender o escopo do sistema. Nossas rotas não podem permitir que qualquer valor de id seja passado.
Quando o usuário faz o login, ele recebe o token de autenticação.
Quando validamos esse token, adicionamos uma propriedade na request chamada User, que armazena as informações de identificação única do usuário, nesse caso, id e email. É de lá que vamos recuperar o id.
Criei um decorator para facilitar a recuperação desses dados, então não é necessário fazer essa alteração agora, mas deixei o comentário para contextualizar.

2024-09-26 20:45 UTC, jauregao commented on src/users/users.controller.ts
> +    return { message: 'User created successfully!' };
No controller devemos retornar os dados não sensíveis do usuário em formato JSON com o status code apropriado em **todos** os endpoints.

2024-09-26 20:45 UTC, jauregao commented on src/users/users.service.ts
> +      throw new NotFoundException(`User with ID ${id} not found`);
Como vamos usar o decorator que recupera dados do usuário do header da requisição, presumimos que a autenticação já foi realizada.
Se o ID não for encontrado, isso indica um problema mais fundamental, como um erro na autenticação ou uma falha na extração do ID do usuário.
Lançar uma exceção aqui pode fazer com que o processo de debug seja mais complexo.

2024-09-26 20:45 UTC, jauregao commented on src/users/users.service.ts
> +      throw new NotFoundException(`User with ID ${id} not found`);
A mesma coisa vale para esse método.

2024-09-26 20:45 UTC, jauregao commented on src/users/users.controller.ts
> +    return await this.usersService.remove(id);
Não se retorna nada em um endpoint de deletar, o que você deve retornar é somente o status code apropriado, nesse caso 204 - No Content.

2024-09-27 15:27 UTC, nanerseasac commented on src/users/users.service.ts
> +      throw new NotFoundException(`User with ID ${id} not found`);
Coloquei a validacao pra garantir que o usuario existe antes de deletar, se nao o prisma vai dar esse tipo de erro ao tentar deletar algo que nao existe, porem fiz oque voce pediu


<img width="960" alt="Screenshot 2024-09-27 at 12 25 32" src="https://github.com/user-attachments/assets/c70a1790-5bb9-42cd-992a-916c3eaa870e">

2024-10-03 20:55 UTC, merged